[tool.poetry]
name = "helloworld-on-gae"
version = "0.1.0"
description = ""
authors = ["moricup"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.30.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
